### ISSUE TITLE
text/number variable="locator" includes a "p." locator label when the associated term is empty

### ISSUE THREAD

**Issue by cormacrelf** [Juris-M/citeproc-js#94]
The following:

```xml
      <term name="page" form="long">
        <single></single>
        <multiple></multiple>
      </term>
      <term name="page" form="symbol">
        <single></single>
        <multiple></multiple>
      </term>
      <term name="page" form="short">
        <single></single>
        <multiple></multiple>
      </term>
```

```xml
<macro name="juris-locator">
  <number variable="locator" prefix="{" suffix="}"/>
</macro>
```

Renders as `{p. 53}`. If you put any content in the 'page' term, then the "p. " goes away. There are two problems here:

1. It seems the engine thinks the entire term is not defined, and runs locale fallback. However, my style wants empty page locators! You can, it seems, put content in the locator and then put choose branches everywhere to prevent the page label ever rendering. The source of the error might be something like `if ("") {} else console.log("empty strings test as false")`.
2. The text or number variable should never include a label. I'm not sure why it would be doing that. That's a pretty significant deviation from spec - maybe there are other problems here?

**Comment by fbennett** [comment]
Thanks for reporting this. The implicit application of labels is by intention, but should not interfere with the ordinary `cs:label + cs:number` or `cs:label + cs:text` syntax. I've fixed this bug in local code, and will release the fix in an updated processor release when I've finished going through a small backlog of fault reports (which should be pretty soon, within a day or two).

**Comment by cormacrelf** [comment]
Why would you intend that? And I was not aware there was anything special about labels followed by text, can’t you render them anywhere and expect them to behave according to how regular labels and text are specified? Like `Group(Group(Label), Group(Text))`?

**Comment by fbennett** [comment]
To clarify, `cs:label + cs:text` in the note above is also meant to refer to rendering of a numeric variable (which can be done through either node type). You can indeed set a label against a numeric variable within a group anywhere, and they will (now that this bug is fixed) behave normally.

Implicit label rendering is meant to address mixed labeling, like "ch. 1 sec. 23, ch. 7, secs. 434-438." It's not needed in most writing, but if support for it does not break ordinary patterns, it's a win in my environment.

**Comment by cormacrelf** [comment]
I’m still not sure I get it — label with a variable attribute knows which label to pull out for “chapter”, so it doesn’t need to be implicit. Same for section. Same for locator. Just put a label element in there. I’m not sure how including labels in the text/number element gets you to the ch/sec example you quote there, given that a reference with a “chapter” variable can only have one of them defined. How are you getting two chapter things in there? When I want to cite like that I just write out a long double-barrelled locator with the locator label set to whatever the first one is. Like {label:”chapter”, locator:”1 sec. 23, ch. 7, secs. 434-438”}.

**Comment by fbennett** [comment]
You can't do this in style code, because the information is all in the locator field. The processor parses the field, scanning for [abbreviated labels](https://citeproc-js.readthedocs.io/en/latest/csl-m/index.html#locator-terms). As you say, you can just write out locators and embedded labels by hand; but the idea (as for use of ref managers generally) is to reduce the need for many small changes across the document when switching between styles.

There are some other issues involved (recognition of an extended set of labels, dual-purposing of the `section` field in CSL-M legal styles, recognition of singular and plural content in the initial numeric element of a mixed-label field), but the main idea is to save time in some environments. (And as I wrote above, that's conditioned on the functionality not getting in the way of users that don't need it or don't want it, of course).

**Comment by fbennett** [comment]
Fixed in tagged release 1.1.211.
